import sys
sys.path.insert(0, '.')
from snowflake_connector import SnowflakeConnector
from pathlib import Path

env_path = Path('../.env')
conn = SnowflakeConnector(env_path)
schema = 'DB_ANALYTICS.SCH_VIRTUALDOM_CLONE'

tests = [
    ('Med Relationship', f"SELECT RELATIONSHIP_TO_EMPLOYEE, YEAR(DIAGNOSIS_DATE) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE DIAGNOSIS_DATE IS NOT NULL GROUP BY 1,2 ORDER BY 2,1"),
    ('Med Gender', f"SELECT PATIENT_GENDER, YEAR(DIAGNOSIS_DATE) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE DIAGNOSIS_DATE IS NOT NULL AND PATIENT_GENDER IS NOT NULL GROUP BY 1,2 ORDER BY 2,1"),
    ('Med Quarter', f"SELECT YEAR(DIAGNOSIS_DATE) as yr, QUARTER(DIAGNOSIS_DATE) as qtr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE DIAGNOSIS_DATE IS NOT NULL GROUP BY 1,2 ORDER BY 1,2 LIMIT 10"),
    ('Pharm Quarter', f"SELECT YEAR(DATE_FILLED) as yr, QUARTER(DATE_FILLED) as qtr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_PHARMACY_DATA WHERE DATE_FILLED IS NOT NULL GROUP BY 1,2 ORDER BY 1,2 LIMIT 10"),
    ('Pharm Relationship', f"SELECT RELATIONSHIP_TO_EMPLOYEE, YEAR(DATE_FILLED) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt FROM {schema}.STG_TAB_PHARMACY_DATA WHERE DATE_FILLED IS NOT NULL GROUP BY 1,2 ORDER BY 2,1 LIMIT 10"),
    ('Hospitalized', f"SELECT HOSPITALIZED_OR_NOT, YEAR(DIAGNOSIS_DATE) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, AVG(TOTAL_EMPLOYER_PAID_AMT) AS mean_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE DIAGNOSIS_DATE IS NOT NULL GROUP BY 1,2 ORDER BY 2,1 LIMIT 10"),
    ('VW_HOSPITAL_VISIT', f"SELECT * FROM {schema}.VW_HOSPITAL_VISIT_STATISTICS LIMIT 3"),
    ('Patient Age groups', f"SELECT CASE WHEN PATIENT_AGE IS NULL THEN 'Unknown' WHEN PATIENT_AGE < 10 THEN '0-9' WHEN PATIENT_AGE < 20 THEN '10-19' WHEN PATIENT_AGE < 30 THEN '20-29' WHEN PATIENT_AGE < 40 THEN '30-39' WHEN PATIENT_AGE < 50 THEN '40-49' WHEN PATIENT_AGE < 60 THEN '50-59' ELSE '60+' END AS age_group, PATIENT_GENDER, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE PATIENT_GENDER IS NOT NULL GROUP BY 1,2 ORDER BY 1,2 LIMIT 15"),
    ('Provider Type', f"SELECT SERVICE_PROVIDER_TYPE_DESCRIPTION, YEAR(DIAGNOSIS_DATE) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, COUNT(DISTINCT MEMBER_ID) AS n FROM {schema}.STG_TAB_MEDICAL_DATA WHERE SERVICE_PROVIDER_TYPE_DESCRIPTION IS NOT NULL GROUP BY 1,2 ORDER BY 2 LIMIT 10"),
    ('Catastrophic', f"SELECT YEAR(DIAGNOSIS_DATE) as yr, COUNT(*) AS claim_count, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt FROM {schema}.STG_TAB_MEDICAL_DATA WHERE TOTAL_EMPLOYER_PAID_AMT > 100000 GROUP BY 1 ORDER BY 1"),
    ('Risk Group Full', f"SELECT RISK_GROUP, FILE_YEAR, SUM(TOTAL_PAID_AMT) AS total_amt, AVG(TOTAL_PAID_AMT) AS mean_amt, COUNT(DISTINCT UNIQUE_ID) AS n FROM {schema}.VW_RISK_GROUP_MIGRATION GROUP BY 1,2 ORDER BY 2,1"),
    ('Chronic Cat', f"SELECT CHRONIC_CAT, FILE_YEAR, SUM(CHRONIC_PAID_AMT) AS total_amt, COUNT(DISTINCT UNIQUE_ID) AS n FROM {schema}.VW_RISK_GROUP_MIGRATION WHERE CHRONIC_CAT IS NOT NULL GROUP BY 1,2 ORDER BY 3 DESC LIMIT 10"),
    ('MPR Full', f"SELECT YEAR, STATIN_FLAG, HYPERTENSION_FLAG, DIABETES_FLAG, AVG(MPR_FINAL)*100 AS avg_mpr, COUNT(DISTINCT UNIQUE_ID) AS n FROM {schema}.VW_MEDICATION_POSSESSION_RATIO GROUP BY 1,2,3,4 ORDER BY 1,2 LIMIT 10"),
    ('Screening Full', f"SELECT YEAR, CANCER_SCREENING, COUNT(DISTINCT UNIQUE_ID) AS eligible_n, SUM(CASE WHEN SCREENING_DATE_MIN IS NOT NULL THEN 1 ELSE 0 END) AS screened_n FROM {schema}.VW_PREVENTIVE_SCREENING GROUP BY 1,2 ORDER BY 1,2"),
    ('Drug Brand', f"SELECT DRUG_INDICATOR_GENERIC_OR_BRAND, YEAR(DATE_FILLED) as yr, SUM(TOTAL_EMPLOYER_PAID_AMT) AS total_amt, COUNT(*) AS n FROM {schema}.STG_TAB_PHARMACY_DATA WHERE DRUG_INDICATOR_GENERIC_OR_BRAND IS NOT NULL GROUP BY 1,2 ORDER BY 2,1"),
]

for name, sql in tests:
    try:
        r = conn.query(sql)
        if r:
            print(f'[OK] {name}: {len(r)} rows, cols={list(r[0].keys())}')
            for row in r[:2]:
                print(f'     {dict(row)}')
        else:
            print(f'[EMPTY] {name}: no data')
    except Exception as e:
        print(f'[ERR] {name}: {str(e)[:120]}')

conn.close()
