name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script: |
            # Navigate to the project directory on your EC2 instance (change 'ubuntu' to your user if needed)
            cd /home/ubuntu/Kairos-Analytics_old
            
            # Pull the newest authenticated code from the main branch
            git pull origin main
            
            # Rebuild and restart the Docker containers in the background
            docker-compose up -d --build
